spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/adaptive_quiz_engine
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  flyway:
    enabled: true
  springdoc:
    swagger-ui:
      enabled: true
    api-docs:
      enabled: true

server:
  port: 8080